### ISSUE TITLE
RegFIBPlusUtils.pas not found when compile FibPlusEditor package

### ISSUE THREAD

**Issue by erickperez1981** [madorin/fibplus#11]
I'm using delphi 7, i compiled FibPlus package fine, but FibPlusEditor not, because there is not RegFIBPlusUtils.pas, this file is required

**Comment by Saschko2000** [comment]
I had the same issue with XE2. I found this: http://www.codelooker.com/codec/8040FIBPlus7.7/regfibplusutils.pas.html

**Comment by wadealer** [comment]
You can just comment out next line at FIBPluseEditors.dpk file :

`regfibplusutils in '..\Editors\RegFIBPlusUtils.pas',`

After that you can compile and install editors.
