### ISSUE TITLE
Firebird 2 and before detecting Firebird 3 packages allowed when it shouldn't

### ISSUE THREAD

**Issue by MayaCKS** [madorin/fibplus#12]
On Firebird 2.5, calling:
pFIBDBSchemaExtract.LoadMetaData(false);

Results in this error:
Column does not belong to referenced table.
SQL error state =42S22
Dynamic SQL Error.
SQL error code = -206.
Column unknown.
RDB$PACKAGE_NAME.
At line 2, column 26.

The problem is with the detection of the availability of the new FB3 packages feature.

This line of code:
  QRY_PACKAGE_SUPPORTS=
 ' SELECT 1 FROM RDB$RELATIONS RF WHERE RF.RDB$RELATION_NAME = ''RDB$RELATIONS'''; 

Needs to change to:
QRY_PACKAGE_SUPPORTS=
' SELECT 1 FROM RDB$RELATIONS RF WHERE RF.RDB$RELATION_NAME = ''RDB$PACKAGES''';

I did create my own branch, but Git won't let me submit a pull request, says project is archived or I don't have permission.

**Comment by madorin** [comment]
@MayaCKS , thanks, fixed
