### ISSUE TITLE
FIBPlus Development

### ISSUE THREAD

**Issue by delphifocus** [madorin/fibplus#20]
I have some question for FIBPlus maintenance code:
1. Can we use this public FIBPlus for commercial project development? 
2. Can you also add the **Tools** source code within this github code?
3. Why not update/increase the **pFIBVersion.inc** after every modification (fix/updating code)?
4. Please update the **changeslog.txt** with every modification.
Thanks a lot.

regards
delphifocus

**Comment by madorin** [comment]
@delphifocus, i'll try to answer to your questions:

1.
* FibPlus is a commercial product based on free open source Fib Components
* It's license allow you to use FibPlus in commercial product, if you bought it
* Currently FibPlus is abandoned, Devrace company was liquidated some years ago
* There is no official explanations from Devrace and/or it's successors
* The goal of this project is to collect patches, sources and maintain the code
* In case of Devrace resurrection/negative reaction or it's successors I will close this repository

2. I do not use Tools in my projects. Feel free to submit the well tested code, including Tools.

3,4. I'll try to do it. Now I'm not an active user of FibPlus, mostly projects in maintenance.
