### ISSUE TITLE
FibPlus не умеет передавать boolean-параметры

### ISSUE THREAD

**Issue by scorpion235** [madorin/fibplus#27]
Окружение:
Delphi 10.2 Update 3 Tokyo Architect
Firebird 3.0.3.32900

В Firebird 3 появился тип данных boolean
Не смог добиться передачи boolean-параметра в Firebird

Передаю из Delphi:
FIBDataSet.ParamByName('PARAM_NAME').AsBoolean := true;
но в Firebird уходит числовое значение 1

Пост на sql.ru: http://www.sql.ru/forum/1295664/fibplus-ne-umeet-peredavat-boolean-parametry
Мой email: scorpion235@mail.ru

**Comment by BerndSchoelzel** [comment]
With this change it works for me.

```
function TFIBXSQLVAR.GetAsBoolean: boolean;
begin
  Result := False;
  if not IsNull then
    case FXSQLVAR^.sqltype and (not 1) of
      SQL_BOOLEAN,SQL_SHORT:
        Result := PShort(FXSQLVAR^.sqldata)^=ISC_TRUE;
     FB3_SQL_BOOLEAN: // BS 25.03.2019 
        Result := PByte(FXSQLVAR^.sqldata)^=ISC_TRUE;
      SQL_LONG:
       Result  := PLong(FXSQLVAR^.sqldata)^=ISC_TRUE;
      SQL_INT64:
       Result  := PInt64(FXSQLVAR^.sqldata)^=ISC_TRUE;
    else
        FIBError(feInvalidDataConversion, [nil])
    end;
end;
```

**Comment by mvb75** [comment]
Аналогичное поведение, ФИБ последний отсюда, Delphi XE2. При выполнении запроса через TpFIBQuery.ExecWP(const ParamValues: array of Variant) с BOOLEAN в параметрах вылазит ошибка:

Project ... raised exception class EFIBInterBaseError with message 'Incompatible column/host variable data type.
SQL error state =22018
Dynamic SQL Error.
SQL error code = -303.
Conversion error from string "0".

Как поправить?

**Comment by mvb75** [comment]
В общем, разобрался, маленькая поправка снимает проблему. 
Модуль: FIBQuery.pas
Метод: procedure TFIBXSQLVAR.SetAsVariant(Value: Variant);
кусок
```
    varBoolean:
      if Value then
        AsVariant := VariantTrue
      else
        AsVariant := VariantFalse;

```
заменить на:
```
    varBoolean:
      case sSQLType of
        FB3_SQL_BOOLEAN: AsBoolean := Value;
        else if Value then
               AsVariant := VariantTrue else
               AsVariant := VariantFalse;
      end;

```

**Comment by mvb75** [comment]
Еще одна поправочка в том же модуле:
`function TFIBXSQLVAR.GetAsBoolean: boolean;
begin
  Result := False;
  if not IsNull then
    case FXSQLVAR^.sqltype and (not 1) of
      SQL_BOOLEAN,SQL_SHORT:
        Result := PShort(FXSQLVAR^.sqldata)^=ISC_TRUE;
      SQL_LONG:
       Result  := PLong(FXSQLVAR^.sqldata)^=ISC_TRUE;
      SQL_INT64:
       Result  := PInt64(FXSQLVAR^.sqldata)^=ISC_TRUE;
      FB3_SQL_BOOLEAN: Result := PBoolean(FXSQLVAR^.sqldata)^ = True;
    else
        FIBError(feInvalidDataConversion, [nil])
    end;
end;`

**Comment by mvb75** [comment]
В редакторе норм показывает, тут чет все в кучу слепил. В общем, думаю, там понятно будет.

**Comment by mvb75** [comment]
Тут, похоже, тоже забросили бедные фибы...
