### ISSUE TITLE
Errors during the compile process FIBPlusEditors2007.dpk.

### ISSUE THREAD

**Issue by vlad-mal** [madorin/fibplus#28]
In during compile process of IBPlusEditors2007.dpk, errors appear, because the .dpk file contains links to missing (and unnecessary) files, for examle -  {$R 'UnitSyntaxMemo.dcr'}

In addition, the file FIBPlusEditors2007.dproj has links to files in a non-existent directory, for example:
    DCCReference Include="RegFIBPlusEditors.pas" 
instead of
    DCCReference Include="..\Editors\RegFIBPlusEditors.pas"
and so on.

Both files are fixed and attached to this issue: [PackagesD2007.zip](https://github.com/madorin/fibplus/files/2088409/PackagesD2007.zip)

Replace them in the project, please.

Regards - Malinovsky Vladimir.

**Comment by madorin** [comment]
Thanks for reporting. I dont have D07 installed so couldnt test it ). Fixed in current branch..
