### ISSUE TITLE
не

### ISSUE THREAD

**Issue by DigLv** [madorin/fibplus#29]
при попытке установить в РадСтудио2010 появляются ошыбки

**Comment by DigLv** [comment]
при попитке установить в РадСтудио2010 появляются ошибки

1) File not found: 'pFIBSyntaxMemo.dcu'

2)  File not found: RegFIBPlusUtils in '..\Editors\RegFIBPlusUtils.pas

3) packages FIBPlusEditors2010 + FIBPlus2010; - синтаксические ошибки
rrequires -- > requires
ocontains -- > contains
d. -- >END.

**Comment by madorin** [comment]
Can you check please if the error still persists? it seems i fixed it in meantime...
