### ISSUE TITLE
pFIBDatabase.pas

### ISSUE THREAD

**Issue by Mike6386** [madorin/fibplus#31]
procedure TpFIBDatabase.RestoreConnect(Sender:TObject);
var
   Actions:TOnLostConnectActions;
   vIsTimer:boolean;
begin
  if Connected then
begin
**StopWaitRestoreConnect;**  // Без этой процедуры vTimer никогда не остановится 
Exit;
end;
...

**Comment by madorin** [comment]
RestoreConnect вызывается автоматически таймером когда коннект не активен. Этот метод даже не должен быть в паблик. Потом дальше в метод таймер останавливается.  Можете вставить WaitForRestoreConnect = 0, и тамер остановится.
