### ISSUE TITLE
FIBPlus Package: RUNONLY directive

### ISSUE THREAD

**Issue by wiphi** [madorin/fibplus#33]
Improve the package compiler direktives for the FIBPlus Runtime-package with the directive
`{$RUNONLY ON}`
see: http://docs.embarcadero.com/products/rad_studio/delphiAndcpp2009/HelpUpdate2/EN/html/devcommon/compdirsrunonlydirective_xml.html

Reason is that the DelphiPI checks the directive for 64bit compiling: https://bitbucket.org/idursun/delphipi/src/master/

**Comment by madorin** [comment]
Well, FibPlus_D* packages are also design time packages, not only runtime package. It actually register basic set of non-visual components without editors. Maybe it will be refactored sometimes but its definetelly not a FibPlus issue, probably DelphiPI should be tuned to handle such cases.

**Comment by wiphi** [comment]
I don't think this is a DelphiPI issue. The `RUNONLY` allows to install and use the package with 64bit apps. Because the IDE is running in 32bit you need 32bit Designtime Packages.
So I have a little workaround to use fibplus with 64bit apps and can use the 32bit editors: 
I copied and rename the package `FIB_Plus_D25.dpk`  to `FIB_Plus_D25_RUN.dpk` (the `*.res` File too). Now I can install booth via Delphi Pi. Maybe the information is interesting for you or for others.

**Comment by madorin** [comment]
okay, ill think on it, it make somehou sence when you need a runtime x64 version of the package to build the app with [x] use runtime packages or load the package dynamically
