### ISSUE TITLE
Fib array fields don't work in recent version

### ISSUE THREAD

**Issue by walxo** [madorin/fibplus#38]
Hi,
Can someone research why array fields don't work in recent fib? I didn't. :(
For information, I'm sending an old FIB for D2007 that works. And a demo program.

[ArrayFields1 Examples.zip](https://github.com/madorin/fibplus/files/3827764/ArrayFields1.Examples.zip)

[FIBPlus 6.9.9 Delphi2007.zip](https://github.com/madorin/fibplus/files/3827766/FIBPlus.6.9.9.Delphi2007.zip)

**Comment by madorin** [comment]
@walxo, what error do you get? unfortunatelly I don't use array fields

**Comment by walxo** [comment]
Hi, Dorin!
This demo I've sent works with EMPLOYEE.FDB, so you can test it. I did printscreen of the error. 
function ArrayFieldValue from the demo goes to unit VariantRtn - function CycleWriteArray and error appears.
I'll appreciate if you can help!

![Untitled](https://user-images.githubusercontent.com/15127971/68545144-e8aeb280-03d2-11ea-926e-92c3ae36fd3f.jpg)

**Comment by madorin** [comment]
@walxo, tried to fix reading of field values in a separate fix-arrays branch, writting still needs investigations. May take a look how it works on your side. I tested it in Rio.

**Comment by walxo** [comment]
@madorin, you are genius! How did you correct it? :):):)

**Comment by madorin** [comment]
Merged into master branch
