### ISSUE TITLE
Database integer default value problem

### ISSUE THREAD

**Issue by Bence98007** [madorin/fibplus#40]
There's a default integer value in database. (TFIBIntegerField)

When inserted a new row into database, the field's validate method occurs, and in this validate method, the default value is not the same as set in database.
TFIBStringField doesn't have this issue, just the TFIBIntegerField.
I'm runnning XE10. It was working on XE2.

Thanks!

**Comment by madorin** [comment]
please provide a test-case application that reproduce this issue for investigations

**Comment by did-vmonroig** [comment]
PR #76 aims to fix this problem.

**Comment by madorin** [comment]
Fixed in #76
