### ISSUE TITLE
Problemas en ejecucion

### ISSUE THREAD

**Issue by fer-intek** [madorin/fibplus#44]
Les consulto, tengo 2 pc, en una funciona todo bien y en la otra puedo compilar bien, pero cuando ejecuto el sistema me da un error: Project xxx.exe raised exception class EOSError with message 'System Error. Code 126. No se puede encontrar el modulo especificado'
Creo que algo tiene que ver con la gds32.dll y fbclient.dll, si alguien me da una mano se lo agradecería.
Uso firebird 2.5 como motor.

**Comment by vkrapotkin** [comment]
I guess you need to specify explicitely which dll you want to use for connection.

**Comment by fer-intek** [comment]
Sos un genio!!! Gracias
