### ISSUE TITLE
const QRY_PACKAGE_SUPPORTS contains wrong RELATION_NAME

### ISSUE THREAD

**Issue by TomcaGitHub** [madorin/fibplus#46]
Hello,
Unit pFibMetada.pas contains wrong relation name at line 930 (RDB$RELATIONS instead of RDB$PACKAGES):

After installation it is as follows:
  QRY_PACKAGE_SUPPORTS=
  ' SELECT 1 FROM RDB$RELATIONS RF WHERE RF.RDB$RELATION_NAME = ''RDB$RELATIONS''';

correct const SQL should be:
  ' SELECT 1 FROM RDB$RELATIONS RF WHERE RF.RDB$RELATION_NAME = ''**RDB$PACKAGES**''';

Tried to connect to a Firebird 2.5 server. 
I experienced that the above issue breaks code completion in SQL editor and also TpFIBDBSchemaExtract.GetDDLText;

[pFIBMetaData.zip](https://github.com/madorin/fibplus/files/5321570/pFIBMetaData.zip)

With Firebird 3 and above there may be no problems.

Thank you.

Best regards,
Tomca

**Comment by madorin** [comment]
Related to #12 , fixed
