### ISSUE TITLE
validation

### ISSUE THREAD

**Issue by JBerta-Procode** [madorin/fibplus#57]
If i set  on field OnValidate, the value becomes empty. This problem appears on any type of field

**Comment by JBerta-Procode** [comment]
Previously (now i use delphi 10.4 sydney, i used 10 delphi before) there was no such problem

**Comment by Loucif-Fouad** [comment]
I Have the same problem using 10.3.3

**Comment by ruben-marti** [comment]
I have the same problem using 10.1 Berlin. 
I've managed to fix part of the problem by creating a new buffer in TFIBCustomDataSet.DoFieldValidate, but I think it's a design issue by changing how TDataset works in modern versions of Delphi.

**Comment by OLMIG62** [comment]
same as issue TFIBxxxfield.OnValidate might dump #30, pls see my comment (and solution)

**Comment by madorin** [comment]
Fixed in #76
