### ISSUE TITLE
FIB Editor not displaying correctly

### ISSUE THREAD

**Issue by kvrsoft** [madorin/fibplus#68]
![изображение](https://user-images.githubusercontent.com/2216785/186883354-28694eaa-d77f-4f7c-8e49-ef246b217450.png)
At the moment FIB Editor does not display all functions.

Though in source codes all necessary windows are present.

![изображение](https://user-images.githubusercontent.com/2216785/186883657-cf4530e6-23a0-4a99-9d7e-891f3f9fbc72.png)

**Comment by topcodesoft** [comment]
This situation is happened when in design mode you have no database connection, or dbname/user/pass/server or port are incorrect. It is not error in FIB.

**Comment by kvrsoft** [comment]
Thank you! That was the problem.
