### ISSUE TITLE
Can't find by name lookup field with type TFIBWideStringField

### ISSUE THREAD

**Issue by RonaldsR** [madorin/fibplus#73]
Fix:

function TFIBWideStringField.GetAsString: string;
begin
if fieldKind=fkData then
   if GetDataToReserveBuffer then
     Result:=PWideChar(FReservedBuffer)
   else
     Result:=''
     else Result:=inherited;  //Use inherited when field not fkData.
end;

**Comment by madorin** [comment]
@RonaldsR , fixed, thanks!
